version: 2.1

jobs:
  build:
    #working_directory: /checkout
    #docker:
    #- image: docker
    #environment:
    #TEST: true
    machine:
      image: ubuntu-1604:201903-01

    resource_class: medium

    environment:
      QEMU_USER_STATIC_VERSION: "v4.1.0-1"

    steps:
      - checkout
        #- setup_remote_docker

      - run:
          name: Install dependencies for multiarch
          command: |
            for target_arch in aarch64 arm x86_64; do
              wget -N https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_USER_STATIC_VERSION}/qemu-${target_arch}-static.tar.gz
              tar -xvf qemu-${target_arch}-static.tar.gz
              rm -f qemu-${target_arch}-static.tar.gz
              sudo mv qemu-${target_arch}-static /usr/bin
            done
            docker run --rm --privileged multiarch/qemu-user-static:register

      - run:
          name: Build electrs
          command: ./build.sh images/electrs
          no_output_timeout: 1h

workflows:
  version: 2
  ci:
    jobs:
      - build
