version: 2.1

jobs:
  build:
    #working_directory: /checkout
    #docker:
    #- image: docker
    #environment:
    #TEST: true
    machine:
      image: ubuntu-1604:201903-01

    resource_class: medium

    environment:
      TEST1: "1.13.1"
      TEST2: v1.15.3

    steps:
      - checkout
        #- setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update -y 
            sudo apt-get install -y qemu-user-static
            dpkg -L qemu-user-static

      - run:
          name: Build electrs
          command: ./build.sh images/electrs

workflows:
  version: 2
  ci:
    jobs:
      - build
